on: 
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: psf/black@stable
        with:
          options: "--verbose"
          src: "tableauserverclient tests samples"
          use_pyproject: true
      - uses: actions/checkout@v4
      - run: |
          black
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "auto-format with black"
          git push
