name: 💬 🚀

on: [push, pull_request, workflow_dispatch]

jobs:
  slack-notifications:
    continue-on-error: true
    runs-on: ubuntu-20.04
    name: Sends a message to Slack when a push, a pull request or an issue is made
    if: ${{ github.ref.name }} == 'master' or ${{ github.event.base_ref }} == "refs/head/master" 
    steps:
      - name: Do nothing
        run: echo "The result was ${{ steps.notify.outputs.slack-result }}"
