name: Be transparent

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  always:
    name: Build a shed
    runs-on: ubuntu-latest
    steps:
      - name: Tell me what's going on here
        run: echo '${{ toJSON(github) }}'
  sometimes:
    name: Build a castle
    if: ${{ github.ref.name }} == 'master' or ${{ github.event.base_ref }} == "refs/head/master" 
    runs-on: ubuntu-latest
    steps:
      - name: Tell me what's going on here
        run: | 
          echo '${{ github.event.base_ref }}'
          echo '${{ github.ref.name }}'
          echo '${{ toJSON(github) }}'
          
